/**
 * Converts Mintlify docs.json into framework config.
 *
 * This is the proof that the navigation port is mechanical rather than
 * hand-work: docs.json's products > tabs > groups > pages tree (arbitrarily
 * nested) becomes a Starlight sidebar and a Fumadocs meta.json set, plus the
 * 93 redirects, with no manual transcription.
 *
 * Usage: node prototypes/tools/gen-config.mjs [--only-prototype-pages]
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '../..');
const docs = JSON.parse(fs.readFileSync(path.join(ROOT, 'docs.json'), 'utf8'));
const onlyProto = process.argv.includes('--only-prototype-pages');

const protoPages = new Set(
  JSON.parse(fs.readFileSync(path.join(ROOT, 'prototypes/pages.json'), 'utf8')).pages
);
const keep = (p) => !onlyProto || protoPages.has(p);

/** Walk Mintlify's nested group structure into Starlight sidebar entries. */
function toSidebar(node) {
  if (typeof node === 'string') return keep(node) ? { slug: node } : null;
  if (Array.isArray(node)) return node.map(toSidebar).filter(Boolean);
  if (node && typeof node === 'object') {
    const label = node.group ?? node.tab ?? node.product ?? node.anchor;
    const kids = node.pages ?? node.groups ?? node.tabs ?? null;
    if (label && kids) {
      const items = toSidebar(kids);
      return items.length ? { label, collapsed: true, items } : null;
    }
    if (kids) return toSidebar(kids);
  }
  return null;
}

const sidebar = (docs.navigation.products ?? [])
  .flatMap((prod) => toSidebar(prod.tabs ?? prod) ?? [])
  .filter(Boolean);

// Mintlify global anchors are top-level links, not tree nodes.
const anchors = (docs.navigation.global?.anchors ?? []).map((a) => ({
  label: a.anchor,
  link: a.href.replace('https://relevanceai.com/docs', ''),
}));

// Redirects split into two classes, because they cannot all live in one place:
//
//   * 79 exact redirects  -> Astro's static `redirects` config (emits stub HTML)
//   * 14 WILDCARD redirects -> host-level only. Astro's static redirects do NOT
//     support `:slug*` / `*`; left in the Astro config it writes a literal
//     file named `:slug*.html`. These map whole subtrees from the pre-reorg
//     IA, so losing them would 404 entire sections of the old site.
//
// Both Cloudflare Pages (_redirects) and Vercel (vercel.json) handle wildcards,
// so the redirect layer is host-coupled no matter which framework wins.
const isWildcard = (r) => /[*:]/.test(r.source) || /[*:]/.test(r.destination);
const all = docs.redirects ?? [];
const exact = all.filter((r) => !isWildcard(r));
const wildcard = all.filter(isWildcard);

const withBase = (p) => `/docs${p}`.replace(/\/+/g, '/');

// Astro `redirects` keys are base-relative, so no /docs prefix here.
const redirects = Object.fromEntries(exact.map((r) => [r.source, r.destination]));

// Cloudflare _redirects: `*` + `:splat`. Mintlify's `:slug*` means the same.
const toCloudflare = (p) => withBase(p).replace(/:\w+\*/g, '*').replace(/(?<!:)\*/g, '*');
const cfLine = (r) => {
  const from = toCloudflare(r.source);
  const to = withBase(r.destination).replace(/:\w+\*/g, ':splat').replace(/\*/g, ':splat');
  return `${from}  ${to}  301`;
};

// Vercel keeps Mintlify's own `:slug*` syntax verbatim.
const vercel = {
  redirects: all.map((r) => ({
    source: withBase(r.source),
    destination: withBase(r.destination),
    permanent: true,
  })),
};

const banner = '// GENERATED by prototypes/tools/gen-config.mjs from docs.json. Do not edit.\n';
const out = (rel, body) => {
  const f = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(f), { recursive: true });
  fs.writeFileSync(f, banner + body);
};

out('prototypes/starlight/sidebar.generated.mjs',
  `export default ${JSON.stringify([...sidebar, ...anchors], null, 2)};\n`);
out('prototypes/starlight/redirects.generated.mjs',
  `export default ${JSON.stringify(redirects, null, 2)};\n`);

// Cloudflare/Netlify _redirects -- exact rules first, wildcards last, since
// Cloudflare matches top-down and a wildcard would otherwise shadow an exact.
const redirectFile =
  [...exact.map(cfLine), '', '# wildcard subtree redirects', ...wildcard.map(cfLine)]
    .join('\n') + '\n';
fs.mkdirSync(path.join(ROOT, 'prototypes/starlight/public'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'prototypes/starlight/public/_redirects'), redirectFile);
out('prototypes/vercel.redirects.json', JSON.stringify(vercel, null, 2) + '\n');

const countLeaves = (n) => Array.isArray(n)
  ? n.reduce((a, x) => a + countLeaves(x), 0)
  : n?.items ? countLeaves(n.items) : (n?.slug ? 1 : 0);

console.log(`sidebar groups : ${sidebar.length}`);
console.log(`sidebar pages  : ${countLeaves(sidebar)}`);
console.log(`global anchors : ${anchors.length}`);
console.log(`redirects      : ${all.length} (${exact.length} exact, ${wildcard.length} wildcard)`);
console.log(`  exact -> astro config; wildcard -> host rules only`);
