/**
 * Converts Mintlify docs.json into framework config.
 *
 * This is the proof that the navigation port is mechanical rather than
 * hand-work: docs.json's products > tabs > groups > pages tree (arbitrarily
 * nested) becomes a Starlight sidebar and a Fumadocs meta.json set, plus the
 * 93 redirects, with no manual transcription.
 *
 * Usage: node prototypes/tools/gen-config.mjs [--only-prototype-pages]
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '../..');
const docs = JSON.parse(fs.readFileSync(path.join(ROOT, 'docs.json'), 'utf8'));
const onlyProto = process.argv.includes('--only-prototype-pages');

const protoPages = new Set(
  JSON.parse(fs.readFileSync(path.join(ROOT, 'prototypes/pages.json'), 'utf8')).pages
);
const keep = (p) => !onlyProto || protoPages.has(p);

/** Walk Mintlify's nested group structure into Starlight sidebar entries. */
function toSidebar(node) {
  if (typeof node === 'string') return keep(node) ? { slug: node } : null;
  if (Array.isArray(node)) return node.map(toSidebar).filter(Boolean);
  if (node && typeof node === 'object') {
    const label = node.group ?? node.tab ?? node.product ?? node.anchor;
    const kids = node.pages ?? node.groups ?? node.tabs ?? null;
    if (label && kids) {
      const items = toSidebar(kids);
      return items.length ? { label, collapsed: true, items } : null;
    }
    if (kids) return toSidebar(kids);
  }
  return null;
}

const sidebar = (docs.navigation.products ?? [])
  .flatMap((prod) => toSidebar(prod.tabs ?? prod) ?? [])
  .filter(Boolean);

// Mintlify global anchors are top-level links, not tree nodes.
const anchors = (docs.navigation.global?.anchors ?? []).map((a) => ({
  label: a.anchor,
  link: a.href.replace('https://relevanceai.com/docs', ''),
}));

// Redirects split into two classes, because they cannot all live in one place:
//
//   * 79 exact redirects  -> Astro's static `redirects` config (emits stub HTML)
//   * 14 WILDCARD redirects -> host-level only. Astro's static redirects do NOT
//     support `:slug*` / `*`; left in the Astro config it writes a literal
//     file named `:slug*.html`. These map whole subtrees from the pre-reorg
//     IA, so losing them would 404 entire sections of the old site.
//
// Both Cloudflare Pages (_redirects) and Vercel (vercel.json) handle wildcards,
// so the redirect layer is host-coupled no matter which framework wins.
const isWildcard = (r) => /[*:]/.test(r.source) || /[*:]/.test(r.destination);
const all = docs.redirects ?? [];
const exact = all.filter((r) => !isWildcard(r));
const wildcard = all.filter(isWildcard);

const withBase = (p) => `/docs${p}`.replace(/\/+/g, '/');

// Astro `redirects` keys are base-relative, so no /docs prefix here.
const redirects = Object.fromEntries(exact.map((r) => [r.source, r.destination]));

// Cloudflare _redirects: `*` + `:splat`. Mintlify's `:slug*` means the same.
const toCloudflare = (p) => withBase(p).replace(/:\w+\*/g, '*').replace(/(?<!:)\*/g, '*');
const cfLine = (r) => {
  const from = toCloudflare(r.source);
  const to = withBase(r.destination).replace(/:\w+\*/g, ':splat').replace(/\*/g, ':splat');
  return `${from}  ${to}  301`;
};

// Vercel keeps Mintlify's own `:slug*` syntax verbatim.
const vercel = {
  redirects: all.map((r) => ({
    source: withBase(r.source),
    destination: withBase(r.destination),
    permanent: true,
  })),
};

const banner = '// GENERATED by prototypes/tools/gen-config.mjs from docs.json. Do not edit.\n';
const out = (rel, body) => {
  const f = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(f), { recursive: true });
  fs.writeFileSync(f, banner + body);
};

out('prototypes/starlight/sidebar.generated.mjs',
  `export default ${JSON.stringify([...sidebar, ...anchors], null, 2)};\n`);
out('prototypes/starlight/redirects.generated.mjs',
  `export default ${JSON.stringify(redirects, null, 2)};\n`);

// Cloudflare/Netlify _redirects -- exact rules first, wildcards last, since
// Cloudflare matches top-down and a wildcard would otherwise shadow an exact.
const redirectFile =
  [...exact.map(cfLine), '', '# wildcard subtree redirects', ...wildcard.map(cfLine)]
    .join('\n') + '\n';
fs.mkdirSync(path.join(ROOT, 'prototypes/starlight/public'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'prototypes/starlight/public/_redirects'), redirectFile);
out('prototypes/vercel.redirects.json', JSON.stringify(vercel, null, 2) + '\n');

// ---- Fumadocs navigation -------------------------------------------------
// Fumadocs builds its sidebar from a meta.json per directory, not one central
// tree, so docs.json has to be projected onto the folder layout. Without this
// it falls back to auto-generating nav from folder names, which loses
// docs.json's grouping and ordering entirely.
function emitFumadocsMeta(nodes) {
  // dir -> { pages: [...], title }
  const dirs = new Map();
  const ensure = (d) => {
    if (!dirs.has(d)) dirs.set(d, { pages: [], groups: new Map() });
    return dirs.get(d);
  };

  const place = (node, dir) => {
    if (node?.slug) {
      if (!keep(node.slug)) return;
      const rel = path.posix.relative(dir, node.slug);
      ensure(dir).pages.push(rel);
      return;
    }
    if (node?.items) {
      // A group maps to a folder when its pages share one, else to a
      // separator plus inline links in the parent meta.
      const slugs = [];
      const collect = (n) => n.slug ? slugs.push(n.slug) : (n.items ?? []).forEach(collect);
      node.items.forEach(collect);
      const kept = slugs.filter(keep);
      if (kept.length === 0) return;

      const common = kept.reduce((acc, s) => {
        const a = acc.split('/'), b = s.split('/'), out = [];
        for (let i = 0; i < Math.min(a.length, b.length) - 0; i++) {
          if (a[i] === b[i]) out.push(a[i]); else break;
        }
        return out.join('/');
      }, kept[0].split('/').slice(0, -1).join('/'));

      if (common && kept.every((s) => s.startsWith(common + '/'))) {
        ensure(dir).pages.push(path.posix.relative(dir, common));
        const g = ensure(common);
        g.title = node.label;
        node.items.forEach((c) => place(c, common));
      } else {
        ensure(dir).pages.push(`---${node.label}---`);
        node.items.forEach((c) => place(c, dir));
      }
    }
  };

  nodes.forEach((n) => place(n, ''));

  let written = 0;
  for (const [dir, cfg] of dirs) {
    const meta = { pages: [...new Set(cfg.pages)] };
    if (cfg.title) meta.title = cfg.title;
    const f = path.join(ROOT, 'prototypes/fumadocs/content/docs', dir, 'meta.json');
    fs.mkdirSync(path.dirname(f), { recursive: true });
    fs.writeFileSync(f, JSON.stringify(meta, null, 2) + '\n');
    written++;
  }
  return written;
}

const metaCount = emitFumadocsMeta(sidebar);

const countLeaves = (n) => Array.isArray(n)
  ? n.reduce((a, x) => a + countLeaves(x), 0)
  : n?.items ? countLeaves(n.items) : (n?.slug ? 1 : 0);

console.log(`sidebar groups : ${sidebar.length}`);
console.log(`sidebar pages  : ${countLeaves(sidebar)}`);
console.log(`global anchors : ${anchors.length}`);
console.log(`fumadocs meta  : ${metaCount} meta.json files`);
console.log(`redirects      : ${all.length} (${exact.length} exact, ${wildcard.length} wildcard)`);
console.log(`  exact -> astro config; wildcard -> host rules only`);
