import { Inter, Sora } from 'next/font/google';
import { Provider } from '@/components/provider';
import { source } from '@/lib/source';
import { DocsLayout } from 'fumadocs-ui/layouts/docs';
import { baseOptions } from '@/lib/layout.shared';
import type { Metadata } from 'next';
import { siteUrl, SITE_NAME } from '@/lib/shared';
import { Analytics } from '@/components/site/analytics';
import { ChatWidget } from '@/components/site/chat-widget';
import './global.css';
// Font Awesome Free, subset to the ~280 icons this site actually renders and
// bundled with the rest of the CSS. The full stylesheet from cdnjs was a
// render-blocking cross-origin request pulling a 158 KB webfont for 1,976
// glyphs -- see tools/build-icon-font.mjs.
import './icons.css';
import './relevance.css';

// Brand typefaces from relevanceai.com: Sora for headings, Inter for UI/body.
const inter = Inter({ subsets: ['latin'], variable: '--font-inter', display: 'swap' });
const sora = Sora({ subsets: ['latin'], variable: '--font-sora', display: 'swap', weight: ['400', '500', '600'] });

/**
 * Site-wide metadata, matched against what Mintlify emits today so the
 * migration is SEO-neutral.
 *
 * metadataBase anchors every relative metadata URL (og:image in particular)
 * to the real origin instead of localhost. The title template reproduces
 * Mintlify's "<Page> - Relevance AI Documentation" format exactly: dropping
 * the suffix would rewrite every SERP title on 289 indexed pages, and bare
 * titles like "Introduction" are far less distinctive.
 */
export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    template: `%s - ${SITE_NAME}`,
    default: SITE_NAME,
  },
  openGraph: {
    siteName: SITE_NAME,
    type: 'website',
    locale: 'en_US',
  },
  twitter: { card: 'summary_large_image' },
  /**
   * Mintlify generates and injects a full favicon set; nothing did that
   * here, so the build declared no icon tags at all and the tab icon was
   * lost. Generated by tools/gen-favicons.mjs from public/favicon.png.
   *
   * Paths are written with the /docs prefix because these are raw public
   * assets: assetPrefix applies to _next chunks, not to metadata icon URLs.
   */
  icons: {
    icon: [
      { url: '/docs/favicon.ico', sizes: 'any' },
      { url: '/docs/favicon-16x16.png', type: 'image/png', sizes: '16x16' },
      { url: '/docs/favicon-32x32.png', type: 'image/png', sizes: '32x32' },
      { url: '/docs/favicon-48x48.png', type: 'image/png', sizes: '48x48' },
      { url: '/docs/android-chrome-192x192.png', type: 'image/png', sizes: '192x192' },
    ],
    apple: [{ url: '/docs/apple-touch-icon.png', sizes: '180x180' }],
    shortcut: ['/docs/favicon.ico'],
  },
};

/**
 * Organization + WebSite structured data. Mintlify injects equivalent
 * JSON-LD on every page; without it we would drop those signals at cutover.
 */
const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Organization',
      '@id': `${siteUrl}/#organization`,
      name: 'Relevance AI',
      url: siteUrl,
      logo: { '@type': 'ImageObject', url: `${siteUrl}/docs/images/logo/light.png` },
      sameAs: [
        'https://twitter.com/relevanceai_',
        'https://github.com/relevanceai',
        'https://linkedin.com/company/relevanceai',
      ],
    },
    {
      '@type': 'WebSite',
      '@id': `${siteUrl}/docs/#website`,
      name: SITE_NAME,
      url: `${siteUrl}/docs`,
      publisher: { '@id': `${siteUrl}/#organization` },
    },
  ],
};

export default function Layout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${inter.variable} ${sora.variable}`} suppressHydrationWarning>
      <head>
        <script
          type="application/ld+json"
          // Static, build-time constant -- no user input reaches this.
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="flex flex-col min-h-screen">
        <a className="rl-skip" href="#nd-page">Skip to main content</a>
        <Provider>
          <DocsLayout tree={source.getPageTree()} {...baseOptions()}>
            {children}
          </DocsLayout>
        </Provider>
        <Analytics />
        <ChatWidget />
      </body>
    </html>
  );
}
