import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import { Provider } from '@/components/provider';
import { source } from '@/lib/source';
import { DocsLayout } from 'fumadocs-ui/layouts/notebook';
import { baseOptions } from '@/lib/layout.shared';
import { getProducts } from '@/lib/products';
import type { Metadata } from 'next';
import { siteUrl, SITE_NAME } from '@/lib/shared';
import { Analytics } from '@/components/site/analytics';
import { ChatWidget } from '@/components/site/chat-widget';
import Script from 'next/script';
import './global.css';
// Font Awesome Free, subset to the ~280 icons this site actually renders and
// bundled with the rest of the CSS. The full stylesheet from cdnjs was a
// render-blocking cross-origin request pulling a 158 KB webfont for 1,976
// glyphs -- see tools/build-icon-font.mjs.
import './icons.css';
import './relevance.css';

/*
 * Inter only. Mintlify sets headings in the body face, so the Sora display
 * face that the marketing-brand pass introduced is no longer referenced by any
 * rule -- keeping it would download a second family on every page for nothing.
 */
/* Italic too: Mintlify loads Inter's real italic, which sets wider than the
   upright face slanted -- without it an italic line that wraps there fit on
   one line here (every quoted example prompt is italic). */
const inter = Inter({ subsets: ['latin'], style: ['normal', 'italic'], variable: '--font-inter', display: 'swap' });

/*
 * Paper Mono is Mintlify's monospace -- every code block, inline code span and
 * API field name is set in it. It is SIL OFL 1.1, taken from the upstream
 * repository (paper-design/paper-mono, fonts/webfonts), not from Mintlify's
 * CDN; the licence travels with it in app/fonts/PaperMono-OFL.txt. Variable,
 * weights 100-800, 53 KB.
 */
const paperMono = localFont({
  src: './fonts/PaperMono-Variable.woff2',
  variable: '--font-paper-mono',
  weight: '100 800',
  display: 'swap',
  fallback: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
});

/**
 * Site-wide metadata, matched against what Mintlify emits today so the
 * migration is SEO-neutral.
 *
 * metadataBase anchors every relative metadata URL (og:image in particular)
 * to the real origin instead of localhost. The title template reproduces
 * Mintlify's "<Page> - Relevance AI Documentation" format exactly: dropping
 * the suffix would rewrite every SERP title on 289 indexed pages, and bare
 * titles like "Introduction" are far less distinctive.
 */
export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    template: `%s - ${SITE_NAME}`,
    default: SITE_NAME,
  },
  openGraph: {
    siteName: SITE_NAME,
    type: 'website',
    locale: 'en_US',
  },
  twitter: { card: 'summary_large_image' },
  /**
   * Mintlify generates and injects a full favicon set; nothing did that
   * here, so the build declared no icon tags at all and the tab icon was
   * lost. Generated by tools/gen-favicons.mjs from public/favicon.png.
   *
   * Paths are written with the /docs prefix because these are raw public
   * assets: assetPrefix applies to _next chunks, not to metadata icon URLs.
   */
  icons: {
    icon: [
      { url: '/docs/favicon.ico', sizes: 'any' },
      { url: '/docs/favicon-16x16.png', type: 'image/png', sizes: '16x16' },
      { url: '/docs/favicon-32x32.png', type: 'image/png', sizes: '32x32' },
      { url: '/docs/favicon-48x48.png', type: 'image/png', sizes: '48x48' },
      { url: '/docs/android-chrome-192x192.png', type: 'image/png', sizes: '192x192' },
    ],
    apple: [{ url: '/docs/apple-touch-icon.png', sizes: '180x180' }],
    shortcut: ['/docs/favicon.ico'],
  },
};

/**
 * Organization + WebSite structured data. Mintlify injects equivalent
 * JSON-LD on every page; without it we would drop those signals at cutover.
 */
const jsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Organization',
      '@id': `${siteUrl}/#organization`,
      name: 'Relevance AI',
      url: siteUrl,
      logo: { '@type': 'ImageObject', url: `${siteUrl}/docs/images/logo/light.png` },
      sameAs: [
        'https://twitter.com/relevanceai_',
        'https://github.com/relevanceai',
        'https://linkedin.com/company/relevanceai',
      ],
    },
    {
      '@type': 'WebSite',
      '@id': `${siteUrl}/docs/#website`,
      name: SITE_NAME,
      url: `${siteUrl}/docs`,
      publisher: { '@id': `${siteUrl}/#organization` },
    },
  ],
};

export default function Layout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="en" className={`${inter.variable} ${paperMono.variable}`} suppressHydrationWarning>
      <head>
        <script
          type="application/ld+json"
          // Static, build-time constant -- no user input reaches this.
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="flex flex-col min-h-screen">
        <a className="rl-skip" href="#nd-page">Skip to main content</a>
        <Provider>
          {/*
            * Mintlify's chrome is a top navigation bar with the brand, search
            * and the Log In / Sign Up pair, and a horizontal row of product
            * tabs under it. Fumadocs' plain `docs` layout has neither: it
            * folds all of that into the sidebar and nests every tab as a
            * collapsible section, which is why the site read as a different
            * product even though the content was byte-identical.
            *
            * The `notebook` layout is the one that renders both. `tabs` is
            * derived from the page tree's root folders, which gen-nav.mjs
            * builds straight from docs.json -- so the tab row is still
            * docs.json's `tabs`, in docs.json's order, with no second list to
            * maintain.
            */}
          <DocsLayout
            tree={source.getPageTree()}
            {...baseOptions()}
            nav={{ ...baseOptions().nav, mode: 'top' }}
            tabMode="navbar"
            /*
             * The tab row belongs to the "Product" product. Every other product
             * (today, the SDK) is reached from the navbar switcher instead and
             * has no tabs of its own -- Mintlify shows six tabs, not seven.
             */
            tabs={{
              transform: (option) => {
                const url = option.url ?? '';
                const other = getProducts().some((p) => p.prefix && (url === p.prefix || url.startsWith(`${p.prefix}/`)));
                return other ? null : option;
              },
            }}
            /* Otherwise this is an unnamed "complementary" landmark. */
            sidebar={{ 'aria-label': 'Documentation navigation' }}
          >
            {children}
          </DocsLayout>
        </Provider>
        <Analytics />
        <ChatWidget />
        {/* Blobby, the live badge inside .invent-callout bubbles. Mintlify
            auto-loaded any .js at the repo root; nothing does that here, so
            the same file is served from public/ and loaded explicitly. It
            no-ops on pages without a bubble and re-mounts on SPA navigation. */}
        <Script src="/docs/invent-callout.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
